import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { Stack, router } from 'expo-router';
import { api, type Approval } from '../lib/api';

export default function ApprovalsScreen() {
  const [items, setItems] = useState<Approval[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{try{setLoading(true);setError('');setItems((await api.approvals()))}catch(e){setError(e instanceof Error?e.message:'Błąd API')}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  async function decide(id:string,status:'approved'|'rejected'){try{await api.decideApproval(id,status);await load()}catch(e){setError(e instanceof Error?e.message:'Nie udało się zmienić decyzji')}}
  return <View style={s.root}><Stack.Screen options={{headerShown:false}}/><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><View><Text style={s.kicker}>JARVIS / CONTROL</Text><Text style={s.title}>Approvals</Text></View></View>{error?<Text style={s.error}>{error}</Text>:null}{loading?<ActivityIndicator style={{marginTop:30}}/>:<FlatList refreshing={loading} onRefresh={() => void load()} data={items} keyExtractor={(x,i)=>String(x.id??i)} contentContainerStyle={s.list} renderItem={({item})=><View style={s.card}><Text style={s.name}>{item.action}</Text><Text style={s.meta}>{item.status??'pending'}</Text>{item.status === 'pending' && <View style={s.actions}><Pressable onPress={()=>decide(String(item.id),'approved')} style={s.button}><Text style={s.buttonText}>Approve</Text></Pressable><Pressable onPress={()=>decide(String(item.id),'rejected')} style={[s.button,s.reject]}><Text style={s.buttonText}>Reject</Text></Pressable></View>}</View>} ListEmptyComponent={<Text style={s.empty}>Brak oczekujących zatwierdzeń.</Text>}/>}</View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#05070a',paddingTop:54},header:{flexDirection:'row',alignItems:'center',paddingHorizontal:20,paddingBottom:18},back:{fontSize:42,color:'#dce6f0',marginRight:14,lineHeight:42},kicker:{fontSize:10,letterSpacing:2,color:'#657585'},title:{fontSize:28,fontWeight:'700',color:'#f3f7fb'},list:{padding:20,gap:10},card:{backgroundColor:'#0c1118',borderWidth:1,borderColor:'#1b2633',borderRadius:14,padding:16},name:{color:'#f1f5f9',fontSize:16,fontWeight:'600'},meta:{color:'#738191',marginTop:5,fontSize:12},actions:{flexDirection:'row',gap:8,marginTop:14},button:{paddingVertical:10,paddingHorizontal:16,borderRadius:9,backgroundColor:'#182635'},reject:{backgroundColor:'#25171b'},buttonText:{color:'#fff',fontWeight:'600'},empty:{color:'#657585',textAlign:'center',marginTop:30},error:{color:'#ff7b7b',paddingHorizontal:20}});
